name: Core
author: Nathan Fallet
main: me.nathanfallet.zabricraft.Core
load: STARTUP
version: 1.0.0
api-version: 1.20
commands:
  login:
    description: Commande de connexion
  register:
    description: Commande d'inscription
  leaderboard:
    description: Gérer les classements
    permission: zabricraft.leaderboard
  money:
    description: Actualiser et afficher son compte
  spawn:
    description: Se teleporter au spawn
  setspawn:
    description: Definir le point de spawn
    permission: zabricraft.setspawn
